//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.ToaThuocs = new HashSet<ToaThuoc>();
        }

        [DisplayName("Mã bệnh nhân")]
        public string MaBenhNhan { get; set; }
        [DisplayName("Tên bệnh nhân")]

        public string TenBenhNhan { get; set; }
        [DisplayName("Tuổi")]

        public Nullable<int> Tuoi { get; set; }
        [DisplayName("Giới tính")]

        public Nullable<bool> Nam { get; set; }
        [DisplayName("Địa chỉ")]

        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToaThuoc> ToaThuocs { get; set; }
    }
}
