//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietToaThuoc
    {
        public int STT { get; set; }

        

        [DisplayName("Mã thuốc")]
        public string MaThuoc { get; set; }
        [DisplayName("Số lượng")]

        public string SoLuong { get; set; }
        [DisplayName("Liều dùng")]

        public string LieuDung { get; set; }
        [DisplayName("Ghi chú")]

        public string GhiChu { get; set; }
        public int ID { get; set; }

        public virtual Thuoc Thuoc { get; set; }
        public virtual ToaThuoc ToaThuoc { get; set; }
    }
}
