//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phanquyen
    {
        public int idtk { get; set; }
        public int idchucnang { get; set; }
        public string Ghichu { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
