//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuoc()
        {
            this.ChiTietToaThuocs = new HashSet<ChiTietToaThuoc>();
        }
       
        [DisplayName("Mã thuốc")]

        public string MaThuoc { get; set; }
        [DisplayName("Tên thuốc")]

        public string TenThuoc { get; set; }
        [DisplayName("Nước sản xuất")]

        public string NuocSx { get; set; }
        [DisplayName("Đơn giá")]

        public string DonGia { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Hạn sử dụng")]

        public Nullable<System.DateTime> HanSuDung { get; set; }
        [DisplayName("Ghi chú")]

        public string GhiChu { get; set; }
        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToaThuoc> ChiTietToaThuocs { get; set; }
    }
}
